### PR TITLE
Include full display name in legacy XML reports

### LINKED ISSUE #5409: Legacy XML reports generated for `@ParameterizedClass` tests do not contain parameters
This issue stems from #5296 which was closed because the report in question was being generated by Gradle, but the same issue exists in JUnit 6.0.3.

If you have a test using `@ParameterizedClass` and get it to generate legacy reports, the parameters do not appear in the report and you just get lots of duplicate entries for each method.  This makes it hard to tell which parameters failed and hard for other tools to process the report.

## Steps to reproduce

I used the `junit-platform-console-standalone-6.0.3.jar` to run the test from the command-line

The test was:

```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedClass;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.Locale;

import static org.junit.jupiter.api.Assertions.*;

@ParameterizedClass(name="candidate={0}")
@ValueSource(strings = { "first", "second", "third" })
class ClassParamTest {

  private String candidate;

  public ClassParamTest(String candidate) {
    this.candidate = candidate;
  }

  @Test
  void notEmpty() {
    assertFalse(candidate.isEmpty());
  }

  @Test
  void isLowercase() {
    assertEquals(candidate.toLowerCase(Locale.ROOT), candidate);
  }
}
```

The build script was:

```bash
#!/bin/bash
cd ~/code/junit-test
JAR=junit-platform-console-standalone-6.0.3.jar
if [ ! -f "$JAR" ]; then
  curl -fL -o "$JAR" "https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/6.0.3/$JAR"
fi
mkdir -p out/test-classes reports
javac -cp "$JAR" -d out/test-classes test/ClassParamTest.java
java -cp "$JAR:out/test-classes" -jar "$JAR" execute -cp out/test-classes --reports-dir=reports --config=junit.platform.reporting.output.dir=reports --config=junit.platform.reporting.legacy.xml.enabled=true --scan-class-path
```

and the report generated was:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="JUnit Jupiter" tests="6" skipped="0" failures="0" errors="0" time="0.061" hostname="co1devps22.yb.lmax" timestamp="2026-02-26T17:39:08">
<properties>
<property name="file.encoding" value="UTF-8"/>
</properties>
<testcase name="isLowercase()" classname="ClassParamTest" time="0">
<system-out><![CDATA[
unique-id: [engine:junit-jupiter]/[class-template:ClassParamTest]/[class-template-invocation:#2]/[method:isLowercase()]
display-name: isLowercase()
]]></system-out>
</testcase>
<testcase name="isLowercase()" classname="ClassParamTest" time="0">
<system-out><![CDATA[
unique-id: [engine:junit-jupiter]/[class-template:ClassParamTest]/[class-template-invocation:#3]/[method:isLowercase()]
display-name: isLowercase()
]]></system-out>
</testcase>
<testcase name="notEmpty()" classname="ClassParamTest" time="0">
<system-out><![CDATA[
unique-id: [engine:junit-jupiter]/[class-template:ClassParamTest]/[class-template-invocation:#3]/[method:notEmpty()]
display-name: notEmpty()
]]></system-out>
</testcase>
<testcase name="notEmpty()" classname="ClassParamTest" time="0">
<system-out><![CDATA[
unique-id: [engine:junit-jupiter]/[class-template:ClassParamTest]/[class-template-invocation:#2]/[method:notEmpty()]
display-name: notEmpty()
]]></system-out>
</testcase>
<testcase name="notEmpty()" classname="ClassParamTest" time="0">
<system-out><![CDATA[
unique-id: [engine:junit-jupiter]/[class-template:ClassParamTest]/[class-template-invocation:#1]/[method:notEmpty()]
display-name: notEmpty()
]]></system-out>
</testcase>
<testcase name="isLowercase()" classname="ClassParamTest" time="0.013">
<system-out><![CDATA[
unique-id: [engine:junit-jupiter]/[class-template:ClassParamTest]/[class-template-invocation:#1]/[method:isLowercase()]
display-name: isLowercase()
]]></system-out>
</testcase>
<system-out><![CDATA[
unique-id: [engine:junit-jupiter]
display-name: JUnit Jupiter
]]></system-out>
</testsuite>
```

Note that I removed most of the properties as they are not really relevant

I would expect the test names to be something like:

```xml
<testcase name="isLowerCase[first]" classname="ClassParamTest" time="0.019"/>
```

## Context

 - Uses Jupiter 6.0.3

### PR DESCRIPTION
**Pull request by marcphilipp**
Rather than just including the display name of the test, the display
names of all ancestors are now included as well, separated by the `>`
character. This includes display names of parents otherwise not
represented in the legacy XML format (for example, the invocation of a
`@ParameterizedClass`).

Resolves #5409.

### CODE REVIEW

File: junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java [hunk 1]
```diff
@@ -111,8 +115,8 @@ private boolean shouldInclude(TestPlan testPlan, TestIdentifier testIdentifier)
 	private void writeXmlReport(TestIdentifier testIdentifier, Map<TestIdentifier, AggregatedTestResult> tests,
 			Writer out) throws XMLStreamException {
 
-		try (XmlReport report = new XmlReport(out)) {
-			report.write(testIdentifier, tests);
+		try (var report = new XmlReport(out)) {
+			report.write(testIdentifier, tests, this.reportData.getTestPlan());
```
Comment (jbduncan) [inline junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java:119]: I've had a look at `XmlReport` and it looks like it uses `reportData.getTestPlan()` directly in a few places.

Have you considered either:
1. Inlining this parameter, or
2. Replacing all uses of `reportData.getTestPlan()` with this parameter?

**Review by jbduncan — COMMENTED** [review]
Hi @marcphilipp - just a super minor nit, but otherwise this PR looks fantastic to me. Good work! 👍

File: junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java (hunk 1 above)
Comment (marcphilipp) [reply junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java:119]: Thanks for the review! I went with option 1. Done in f71017219088244e623f00c6c24a1d0c6af45032

Comment (jbduncan) [reply junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java:119]: Brilliant, I'm happy with that. Thanks for making the fix so quickly! 👍
