### PR TITLE
Fail on classpath resource names that are blank after removing leading slash

### LINKED ISSUE #4752: ClasspathResourceSelector is more lenient than ClasspathResourceSource
## Steps to reproduce

0. Have a test engine use JUnits `EngineDiscoveryRequestResolver`.
1. Discover with `DiscoverySelectors.selectClasspathResource("/")`.
2. Have the test engine call `.getClasspathResources()` on that selector. This will result in a `PreconditionViolationException`.
4. This exception is then caught by the `EngineDiscoveryRequestResolver` which tries to create an issue for it. 
5. This then fails because the `ClasspathResourceSource` does not accept the empty resource.

To reproduce clone: https://github.com/cucumber/cucumber-java-skeleton and replace the package selector in `RunCucumberTest` with `@SelectClasspathResource("/")`. Observe:

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-platform-suite' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:208)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:174)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:119)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:84)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:104)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:91)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.InterceptingLauncher.lambda$execute$1(InterceptingLauncher.java:39)
	at org.junit.platform.launcher.core.ClasspathAlignmentCheckingLauncherInterceptor.intercept(ClasspathAlignmentCheckingLauncherInterceptor.java:25)
	at org.junit.platform.launcher.core.InterceptingLauncher.execute(InterceptingLauncher.java:38)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:66)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:231)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'cucumber' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:208)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:174)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:119)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:102)
	at org.junit.platform.suite.engine.SuiteLauncher.discover(SuiteLauncher.java:58)
	at org.junit.platform.suite.engine.SuiteTestDescriptor.discover(SuiteTestDescriptor.java:126)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.junit.platform.suite.engine.DiscoverySelectorResolver.discoverSuites(DiscoverySelectorResolver.java:40)
	at org.junit.platform.suite.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:48)
	at org.junit.platform.suite.engine.SuiteTestEngine.discover(SuiteTestEngine.java:60)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:195)
	... 17 more
Caused by: org.junit.platform.commons.PreconditionViolationException: Classpath resource name must not be null or blank
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:298)
	at org.junit.platform.commons.util.Preconditions.notBlank(Preconditions.java:266)
	at org.junit.platform.engine.support.descriptor.ClasspathResourceSource.<init>(ClasspathResourceSource.java:120)
	at org.junit.platform.engine.support.descriptor.ClasspathResourceSource.<init>(ClasspathResourceSource.java:116)
	at org.junit.platform.engine.support.descriptor.ClasspathResourceSource.from(ClasspathResourceSource.java:63)
	at org.junit.platform.launcher.core.DiscoveryIssueCollector.lambda$toSource$1(DiscoveryIssueCollector.java:95)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.platform.launcher.core.DiscoveryIssueCollector.toSource(DiscoveryIssueCollector.java:95)
	at org.junit.platform.launcher.core.DiscoveryIssueCollector.selectorProcessed(DiscoveryIssueCollector.java:69)
	at org.junit.platform.launcher.listeners.discovery.CompositeLauncherDiscoveryListener.lambda$selectorProcessed$4(CompositeLauncherDiscoveryListener.java:61)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at org.junit.platform.launcher.listeners.discovery.CompositeLauncherDiscoveryListener.selectorProcessed(CompositeLauncherDiscoveryListener.java:61)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:103)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:148)
	at io.cucumber.junit.platform.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:32)
	at io.cucumber.junit.platform.engine.FeaturesPropertyResolver.resolveSelectors(FeaturesPropertyResolver.java:52)
	at io.cucumber.junit.platform.engine.CucumberTestEngine.discover(CucumberTestEngine.java:57)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:195)
	... 36 more
```

## Context

With JUnit 5.13.3.

Originally reported as https://github.com/cucumber/cucumber-jvm/issues/3024.

## Deliverables

- [ ] Make `ClasspathResourceSelector` reject the empty classpath resource name.
- [ ] Ensure that Suite Engine reports annotations with the empty resource name as a problem and doesn't throw when doing so.

### PR DESCRIPTION
**Pull request by marcphilipp**
Fixes #4752.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit-framework/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://docs.junit.org/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://docs.junit.org/snapshot/user-guide/) and [Release Notes](https://docs.junit.org/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java [hunk 1]
```diff
@@ -78,7 +78,17 @@ else if (result.getStatus() == UNRESOLVED && selector instanceof UniqueIdSelecto
 		}
 	}
 
-	static @Nullable TestSource toSource(DiscoverySelector selector) {
+	private static @Nullable TestSource toSourceSafely(DiscoverySelector selector) {
+		try {
+			return toSource(selector);
+		}
+		catch (Exception e) {
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java]: This should not be necessary but we should do our best to avoid throwing an exception while reporting a discovery issue.

Comment (mpkorstanje) [reply junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java]: I think this is both too much and not enough.

A broad try-catch would make sense if JUnit would be invoking third-party implementations. But the current the `toSource` method only supports a select number of selector implementations, all owned by JUnit. If the preconditions for those selectors align with those of the test sources, this could never happen. There is not even a test you could write to make this fail.

At the same time, any third-parties can implement custom selectors, but they'll have to do their own issue reporting. 

Would it make sense to add `DiscoverySelector.toTestSource()`? This would allow JUnit to test the `toSource` implementation on its own selectors and would allow third-party selectors to also provide a source.

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java [hunk 2]
```diff
@@ -67,7 +67,7 @@ public void selectorProcessed(UniqueId engineId, DiscoverySelector selector, Sel
 		if (result.getStatus() == FAILED) {
 			this.issues.add(DiscoveryIssue.builder(Severity.ERROR, selector + " resolution failed") //
```
Comment (mpkorstanje) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java]: There is a implicit `toString` call here to a 3rd party implementation which could throw. So the same caution that prompted `toSourceSafely`, should probably put a try-catch around it.

And I only just now realized that `DiscoverySelector.toString()` should have been implemented in Cucumber.  😉

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java (hunk 1 above)
Comment (mpkorstanje) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java]: I would expect a `rethrowIfUnrecoverable` here.

**Review by mpkorstanje — COMMENTED** [review]
I think this will work as expected. 

I've made a suggestion for a `DiscoverySelector.toSource()` method, but that could be pushed to v6.

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java (hunk 1 above)
Comment (marcphilipp) [reply junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java]: Added in 4eb59255fe0d9e1d0aaccd1a5f02e750359b3768

Comment (marcphilipp) [reply junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java]: > A broad try-catch would make sense if JUnit would be invoking third-party implementations. But the current the `toSource` method only supports a select number of selector implementations, all owned by JUnit. If the preconditions for those selectors align with those of the test sources, this could never happen. There is not even a test you could write to make this fail.

There was, actually. :wink: I found another inconsistency with `PackageSelector` which allowed `""` and `PackageSource` which didn't.

Another problem is the normalization that `FileSource` and `DirectorySource` are doing by calling `File.getCanonicalFile()`. For now, I've reduced the scope of the try-catch block to those.

> At the same time, any third-parties can implement custom selectors, but they'll have to do their own issue reporting.

They would still benefit from the built-in issue reporting but the reported discovery issue would not have a `TestSource`.

> Would it make sense to add `DiscoverySelector.toTestSource()`? This would allow JUnit to test the `toSource` implementation on its own selectors and would allow third-party selectors to also provide a source.

I thought about it. I don't remember the specifics but we decided to introduce another `FilePosition` for use in `DiscoverySelector` implementations because they shouldn't reference the one in the `..support.descriptor` package (see https://github.com/junit-team/junit-framework/issues/2146#issuecomment-595215212). If we now introduced `toSource()`, all selector implementations would have to reference that package.

Another option could be to introduce a `ServiceLoader`-based "converter" for `DiscoverySelector` to `TestSource`. But, if this is the only use case, I'm not sure it would be justified. If you feel strongly about needing a solution for third-party selector implementations, please open a new issue and we can discuss it for 6.0 (or later).

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java (hunk 2 above)
Comment (marcphilipp) [reply junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java]: Well, if a `toString()` method throws an exception, I'm happy to let the entire discovery fail for that engine... :hand_over_mouth:

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java (hunk 1 above)
Comment (mpkorstanje) [reply junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DiscoveryIssueCollector.java]: I've got no strong feelings about this.

Oh and nice catch.
